spring:
  application:
    name: my-sfa-app
  
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        
  flyway:
    enabled: false

  security:
    oauth2:
      client:
        registration:

server:
  port: 8080

app:
  jwt:
    secret: testSecretForSwaggerDemo12345678901234567890123456789012345678901234567890
    expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  security:
    enabled: false

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  show-actuator: true
  info:
    title: SalesForge API
    description: Sales Force Automation CRM API
    version: 1.0.0
  servers:
    - url: http://localhost:8080
      description: Development server

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: INFO
    com.example: INFO